# Generated by Django 5.0.2 on 2024-02-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='userID',
            field=models.IntegerField(),
        ),
    ]
